version: '4'
services:
  mysql:
    image: mysql:latest
    container_name: banks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banks
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    ports:
      - "3306:3306"
    volumes:
      - "./db/:/docker-entrypoint-initdb.d/bank_creator.sql"
      